version: 2
updates:
- package-ecosystem: npm
  directory: "/api-server/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/nginx-server/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  
